### ISSUE TITLE
doXdf issue with 0.7

### ISSUE THREAD

**Issue by akzaidi** [RevolutionAnalytics/dplyrXdf#11]
When using `doXdf` with version 0.7, I'm getting the following error:

```
flightsMods <- flightsXdf %>%
     group_by(carrier) %>%
     doXdf(model=rxLinMod(arr_delay ~ dep_delay + hour, data=.))
Error in rxGetFileSystem(.data) : object 'x' not found
```

Can you see if anything broke in the last version when RxLocalParallel support was added?

Thanks.

**Comment by hongooi73** [comment]
Copy-and-paste error, should be fixed now. Thanks for reporting!
