### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ionnoant** [RevolutionAnalytics/dplyrXdf#12]
Hi there! I seem to be having issues installing the dplyrXdf package into RRE. I tried installing the package locally and from GitHub directly and I get the same issue:

` devtools::install_github("RevolutionAnalytics/dplyrXdf")
Downloading GitHub repo RevolutionAnalytics/dplyrXdf@master
from URL https://api.github.com/repos/RevolutionAnalytics/dplyrXdf/zipball/master
Installing dplyrXdf
Skipping 2 unavailable packages: RevoPemaR, RevoScaleR
"C:/PROGRA~1/RRO/R-31~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/ionnoan/AppData/Local/Temp/13/RtmpAHjaHH/devtoolsdec5c752420/RevolutionAnalytics-dplyrXdf-1f70248"  \
  --library="\OEBFS05/Home/IonnoAn/R/win-library/3.1" --install-tests 
- installing _source_ package 'dplyrXdf' ...
  *\* R
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  converting help for package 'dplyrXdf'
    finding HTML links ... done
    as.data.frame                           html  
    deleteXdfTbls                           html  
    distinct                                html  
    do                                      html  
    dplyrXdf                                html  
    finding level-2 HTML links ... done
  
    factorise                               html  
    group_by                                html  
    groups                                  html  
    mutate                                  html  
    persist                                 html  
    rxArgs                                  html  
    setops                                  html  
    summarise                               html  
    tbl                                     html  
    tbl_vars                                html  
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
  Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  there is no package called 'dplyrXdf'
  Error: loading failed
  Execution halted
  ERROR: loading failed
- removing '\OEBFS05/Home/IonnoAn/R/win-library/3.1/dplyrXdf'
  Error: Command failed (1)`

**Comment by hongooi73** [comment]
Per this line in the build process:

> Skipping 2 unavailable packages: RevoPemaR, RevoScaleR

R can't detect that you have Revolution R Enterprise/Microsoft R Server (or Microsoft R Client). Can you check that you do have one of these installed? Note that Revolution R Open/Microsoft R Open doesn't include these packages.

**Comment by ionnoant** [comment]
I definitely have R Enterprise installed and am using some of the functions in the RevoScaleR package. Not sure why this is happening.

**Comment by hongooi73** [comment]
It looks like you also have RRO on your system, and it's ahead of RRE in your path. Make sure that when devtools runs R CMD INSTALL, it's running the correct version of R.

**Comment by ionnoant** [comment]
Not sure how to identify the path the the required RRE folder. If I uninstall RRO will this solve the issue?

**Comment by hongooi73** [comment]
To find out RRE's location, at the R console type `Sys.getenv("R_HOME")`. This will print the root of the RRE install.

Uninstalling RRO should help. You may still have to add RRE to your path for devtools to work, though.
