### ISSUE TITLE
Add HDFS support

### ISSUE THREAD

**Issue by hongooi73** [RevolutionAnalytics/dplyrXdf#14]

**Comment by hongooi73** [comment]
Really depends on how complete HDFS support is in RevoScaleR

**Comment by jaredlander** [comment]
Was this implemented?  Would be awesome to have?  And does this support SQL Server?  I know that's a pipedream but I have to believe.

**Comment by hongooi73** [comment]
Hdfs support is still on the to-do list. Basically there's still some stuff that has to be done on the backend, in particular the ability to join xdf files.

For SQL Server, you can use the RSQLServer package. It's currently been taken off CRAN due to incompatibilities with dplyr, but you can download the [dev version](https://github.com/imanuelcostigan/RSQLServer) from Github. It's just waiting for dplyr to be updated again before being resubmitted to CRAN.

This will get you support for traditional SQL operations, but not calling R in-database (ie anything you might do with `transformFunc`) or using rx* modelling functions. Still, that should be enough for most of what you'd want to do with SQL.

**Comment by jaredlander** [comment]
Thanks for the updates.

`RSQLServer` seems more like it adds another `dplyr` backend so SQL Server can be used same as Postgres.

**Comment by hongooi73** [comment]
@jaredlander it's taken a while, but dplyrXdf should now work with Hadoop and Spark clusters, and data in HDFS. If you're still interested, give it a go and tell me if you run into any problems.
