### ISSUE TITLE
Persist Fails When Overwriting

### ISSUE THREAD

**Issue by jaredlander** [RevolutionAnalytics/dplyrXdf#26]
I haven't thoroughly troubleshooted this but ran into the error today.

I am trying to use `mutate` to create a new variable then overwrite the file.

```r
download.file('http://www.jaredlander.com/data/acs_ny.csv',
              destfile='data/acs_ny.csv')

library(dplyrXdf)

acs <- acs %>% 
    mutate(Income=FamilyIncome >= 120000) %>% 
    persist(outFile=acs, overwrite=TRUE)
```

Then I get this error:
```r
Error in to[okay] : object of type 'S4' is not subsettable
```

**Comment by hongooi73** [comment]
Is `acs` an RxXdfData object?

**Comment by jaredlander** [comment]
Oh yeah, sorry, left out part of the code.  The whole thing is below.

```r
download.file('http://www.jaredlander.com/data/acs_ny.csv',
              destfile='data/acs_ny.csv')

library(dplyrXdf)

acs <- RxXdfData('XDF/acs.xdf')
rxTextToXdf(inFile='data/acs_ny.csv', outFile=acs,
            overwrite=TRUE, stringsAsFactors=FALSE, 
            rowsPerRead=4000)

acs <- acs %>% 
    mutate(Income=FamilyIncome >= 120000) %>% 
    persist(outFile=acs, overwrite=TRUE)
```

```r
Error in to[okay] : object of type 'S4' is not subsettable
```

But `rxDataStep` works.

```r
rxDataStep(inData=acs, outFile=acs, 
           transforms=list(Income=FamilyIncome >= 120000), 
           overwrite=TRUE)
```

**Comment by hongooi73** [comment]
`persist` takes a character string which is the output filename (see the online help). This should work:

    acs %>% mutate(...) %>% persist(acs@file, move=TRUE)

But better would be

    acs %>% mutate(..., .outFile=acs@file)

as this will write the output file as part of the `mutate` step. In some cases, this can save you a significant amount of I/O. In both cases, `overwrite=TRUE` is assumed.

**Comment by jaredlander** [comment]
Interesting.  Tore down the server already but will test that next time.  Thanks!
