### ISSUE TITLE
RevoScaleR:::rxRemoteCopy fails with directories

### ISSUE THREAD

**Issue by hongooi73** [RevolutionAnalytics/dplyrXdf#37]
Will copy the directory, but not the contents

**Comment by hongooi73** [comment]
Need to pass `-r` as switch to pscp

**Comment by Hong-Revo** [comment]
False alarm

**Comment by hongooi73** [comment]
Must also quote source paths if they contain spaces, or scp will fail silently.

**Comment by hongooi73** [comment]
TFS item 78068

**Comment by hongooi73** [comment]
`hdfs_upload`, `hdfs_download`, `copy_to` and `collect` should all handle this now
