### ISSUE TITLE
Bug in creating logical vectors with dplyrXdf

### ISSUE THREAD

**Issue by martenlindblad** [RevolutionAnalytics/dplyrXdf#66]
If I summarise a logical column I get wrong values.
![image](https://user-images.githubusercontent.com/2125615/29869072-aefd7d1a-8d81-11e7-9bfa-6d6d04368dbc.png)
Code to get the vector:
`crimes<- crimesXdf %>% filter(as.Date(Date) == as.Date("2001-01-01"), .outFile = NULL)
test <- crimes$Arrest
`
It seems that the logical vector actually is a string vector.

**Comment by hongooi73** [comment]
Can you post the code you used to create the crimesXdf file and the Arrest column?

**Comment by martenlindblad** [comment]
Arrest is already present in the .csv.

`rxImport('data/crimes_-_2001_to_present.csv', outFile = crimesTmp, quotedDelimiters = TRUE, overwrite = TRUE, transformFunc = date2Date)`

`codes <- rxImport('data/chicago_police_department_-_illinois_uniform_crime_reporting__iucr__codes.csv', quotedDelimiters = TRUE)`

`rxMerge(crimesTmp, codes, outFile = crimesXdf, type = "left_join", matchVars = c('IUCR'), autoSort = TRUE, overwrite = TRUE)`

`crimesXdf <- RxXdfData(crimesFileName)`

**Comment by hongooi73** [comment]
There's no dplyrXdf code in there.

Please note that dplyrXdf is actually separate to the base RevoScaleR package which comes with Microsoft R. dplyrXdf is a shell on top of RevoScaleR that exposes a dplyr-compatible interface. Any function that starts with `rx` is a RevoScaleR function, not dplyrXdf.

You may be experiencing issues with the Revo functions, in which case I suggest posting a question on [StackOverflow](https://stackoverflow.com) with the `microsoft-r` tag. Be sure to include [all the information needed](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) to reproduce the problem. In particular, it would help to be able to show a sample of the data.
