### ISSUE TITLE
Problem installing the library

### ISSUE THREAD

**Issue by FidelCastillo** [RevolutionAnalytics/dplyrXdf#7]
Hi,

I'm a RRE customer and I'm tring to install the library via github using

devtools::install_github("RevolutionAnalytics/dplyrXdf")

> devtools::install_github("RevolutionAnalytics/dplyrXdf")
> Downloading GitHub repo RevolutionAnalytics/dplyrXdf@master
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached

thank you in advice

**Comment by hongooi73** [comment]
Hi, it looks like you have a connectivity problem. Are you able to download and install other packages from CRAN and/or Github?

**Comment by FidelCastillo** [comment]
Hi again,

Thank you for your fast reply.

I'm able to install libraries, and we tried to install dplyrXdf locally with the zip file, and didn't work.

> install.packages("C:/Downloads/dplyrXdf-master.zip", repos = NULL, type = "win.binary")
> Installing package into ‘C:/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> library(dplyrXdf)
> Error in library(dplyrXdf) : there is no package called ‘dplyrXdf’

**Comment by FidelCastillo** [comment]
Now we did... We have blocked the github in our company and when we try to install from the zip we are using the wrong function. 

We fix this using
devtools::install_local("C:/Downloads/dplyrXdf-master.zip")

Thank you for your help... I'm sure that we will ask you some more questions
