### ISSUE TITLE
Install on MRO 3.3.2 under Centos

### ISSUE THREAD

**Issue by jmagosta** [RevolutionAnalytics/dplyrXdf#73]
Installing on Microsoft R Open 3.3.2  via

devtools::install_github("RevolutionAnalytics/dplyrXdf") 

returns the error

ERROR: dependency "rlang" is not available for package "dplyrXdf"

Installing rlang from cran-r gives a "package not available for R version 3.3.2" error

Is there a workaround?

**Comment by hongooi73** [comment]
Resolved via email

**Comment by mdapri** [comment]
Same problem for Microsoft R Open 3.4.1. 
Could you please tell me the workaround applied?
